### ISSUE TITLE
Error on generate

### ISSUE THREAD

**Issue by lubo08** [pascalgrimaud/generator-jhipster-primeng-charts#2]
yo jhipster-primeng-charts
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: this.getJhipsterAppConfig is not a function
    at module.exports.readConfig (/home/lubo08/.nvm/versions/node/v10.16.0/lib/node_modules/generator-jhipster-primeng-charts/generators/app/index.js:29:47)
    at Object.<anonymous> (/home/lubo08/.nvm/versions/node/v10.16.0/lib/node_modules/generator-jhipster-primeng-charts/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:424:27)
    at /home/lubo08/.nvm/versions/node/v10.16.0/lib/node_modules/generator-jhipster-primeng-charts/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/lubo08/.nvm/versions/node/v10.16.0/lib/node_modules/generator-jhipster-primeng-charts/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/lubo08/.nvm/versions/node/v10.16.0/lib/node_modules/generator-jhipster-primeng-charts/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/lubo08/.nvm/versions/node/v10.16.0/lib/node_modules/generator-jhipster-primeng-charts/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by pascalgrimaud** [comment]
@lubo08 : hi, yes it's normal, I didn't update this module for JHipster 6

**Comment by CentroricercheRPS** [comment]
Do you plan to update it?

**Comment by pascalgrimaud** [comment]
@CentroricercheRPS : I don't think so, as I stopped using Angular for my customer. I switch to Vue.js now

You should have a look at this project instead: https://github.com/sudheerj/generator-jhipster-primeng : it's far better than my module and it's maintained !
